jobs:
  test:
    name: Coverage and static check test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1.5"
      
      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup test tools
        run: |
          luarocks install luacheck
          luarocks install busted
          luarocks install luacov

      - name: Check coverage with busted 
        run: busted
  
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{secrets.CODECOV_TOKEN}} # not required for public repos
          files: luacov.stats.out
          fail_ci_if_error: false

      - name: Check static-check with luacheck
        run: luacheck src spec