name: Trigger Upload by empty commit

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'chore: [upload] triggered by workflow'
        required: true
        default: 'Automated empty commit'

permissions:
  contents: write

jobs:
  empty_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Make an empty commit with a custom message
      - name: Make an empty commit
        run: |
          git commit --allow-empty -m "${{ github.event.inputs.commit_message }}"
          git push
